### ISSUE TITLE
recursive error

### ISSUE THREAD

**Issue by euhruska** [msmbuilder/vde#3]
installed on python3
for the example notebook it worked until `mdl.eval()`, where I got 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxx/lib/python3.5/site-packages/sklearn/base.py", line 290, in __repr__
    offset=len(class_name),),)
...
RecursionError: maximum recursion depth exceeded
`
should I reinstall in python2.7 or is the issue elsewhere?

**Comment by cxhernandez** [comment]
I'm using Python 3.5.4 (via Anaconda) and am unable to reproduce that error. You might be able to remove that line though, as it's not entirely necessary. What's weird is that gets called in `transform` and `propagate` anyway, so I'm not sure why it would only throw an error at that specific cell.
