### ISSUE TITLE
settings for 2nd VDE coordinate

### ISSUE THREAD

**Issue by euhruska** [msmbuilder/vde#5]
I wanted to look at the 2nd VDE coordinate and I have set the encoder_size=2, but then the resulting VDE coordinates look more like noise than coordinates, even the 1st VDE coordinate is gone.
Is there a way/setting to get 2 (or more) VDE coordinates?

**Comment by cxhernandez** [comment]
The VDE loss function isn't designed for more than one coordinate currently (even though the option is available). You could set `autocorr` to false (this turns off the autocorrelation loss function) and try it again. This would essentially be a time-lagged VAE.
